### ISSUE TITLE
Add an option to easily set the visual indicators' colors

### ISSUE THREAD

**Issue by indeedwatson** [laurenkt/zsh-vimto#1]
I recently started using this zsh theme: https://github.com/geometry-zsh/geometry and it's nice how you can set various colors with envinroment variables. I have no idea how hard it would be to implement but it would be nice if we could set our own colors for the visual indicators, as useful as it is, the NORMAL tag sticks out a bit too much.

**Comment by laurenkt** [comment]
That does sound like a useful feature and probably not too much of a burden to add, I'll look into it

**Comment by indeedwatson** [comment]
Awesome!

**Comment by laurenkt** [comment]
Well better late than never.. it's been a busy year! Added this feature in 6035d92a72a09143382799226b0bd404c2c052cf, details in the README.
